refactored two img elements to one
AnalogStudiosRI/www.blissfestri.com pull request #39
Opened 2023-04-23 09:53 UTC by Udassi-Pawan

Resolves #34 

## Summary of Changes
I refactored the two img elements to just one conserving the styles.
I am relatively newer to open source contributions. Do let me know if any changes are required.

2023-04-23 18:43 UTC, Arindam200 requested changes

2023-04-23 18:43 UTC, Arindam200 commented on src/components/event-details/event-details.js
> +        <img src="/assets/images/ri-map.webp" class="block pt-2 w-350 sm:pt-0 sm-max-w-sm md:max-w-sm lg:max-w-md xl:max-w-md sm:absolute sm:z-(-1)">
```suggestion
        <img src="/assets/images/ri-map.webp" class="block pt-2 w-[350px] sm:pt-0 sm-max-w-sm md:max-w-sm lg:max-w-md xl:max-w-md sm:absolute sm:z-(-1)">
```

2023-04-23 18:43 UTC, Arindam200 commented on src/components/event-details/event-details.js
> +        <img src="/assets/images/ri-map.webp" class="block pt-2 w-350 sm:pt-0 sm-max-w-sm md:max-w-sm lg:max-w-md xl:max-w-md sm:absolute sm:z-(-1)">
I think w-350 will not work. Instead, you can use `w-[350px]`

2023-04-23 19:26 UTC, Arindam200 commented on src/components/event-details/event-details.js
> +        <img src="/assets/images/ri-map.webp" class="block pt-2 w-350 sm:pt-0 sm-max-w-sm md:max-w-sm lg:max-w-md xl:max-w-md sm:absolute sm:z-(-1)">
```suggestion
        <img src="/assets/images/ri-map.webp" class="block pt-2 w-350 sm:pt-0 sm-max-w-sm md:max-w-sm lg:max-w-md xl:max-w-md sm:absolute sm:z-[-1]">
```

2023-04-23 19:28 UTC, Arindam200 requested changes

2023-04-23 19:28 UTC, Arindam200 commented on src/components/event-details/event-details.js
> +        <img src="/assets/images/ri-map.webp" class="block pt-2 w-350 sm:pt-0 sm-max-w-sm md:max-w-sm lg:max-w-md xl:max-w-md sm:absolute sm:z-(-1)">
And I think it should be `z-[-1]`

2023-04-24 23:11 UTC, thescientist13 reviewed
Thanks @Udassi-Pawan for this!

I realize I forgot to leave out an important detail in the issue 🤦‍♂️ 

So for mobile, we needed to use a second image where the dots keep going down to the logo just because we wanted to keep everything stacked and narrow for these kind of screen sizes.  I have a PR up for this now that I got the latest image from the designer - #40 
![Screen Shot 2023-04-24 at 7 10 11 PM](https://user-images.githubusercontent.com/895923/234135026-1b33b081-3b8b-4536-b438-1202b7e39cc2.png)

This means that we would still need to manage two different `src` attributes based on breakpoint.  I'm thinking we could use [`srcset`](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#resolution_switching_different_sizes) to select which image to load, while still keeping the styles all in Tailwind?  Hopefully that allows us to still use one `<img>` tag.  🤞 

Let me know your thoughts, and apologies for the missing details.

2023-04-29 15:07 UTC, thescientist13 commented
Just wanted to share an example that I just implemented for the header banner image that you can reference
https://github.com/AnalogStudiosRI/www.blissfestri.com/blob/main/src/components/header/header.js#L9
```html
  <img
    src="/assets/images/blissfest-logo-sm.webp"
    srcset="/assets/images/blissfest-logo-sm.webp 500w,
            /assets/images/blissfest-logo-md.webp 1000w,
            /assets/images/blissfest-logo-lg.webp 1500w"
  />
```

In this case I did the following:
1. Set the `src` to the default image to show, which in our case we want to target mobile as the default
1. Create an entry in the source set at each breakpoint I wanted to target; 350px, 1000px, 1500px across three different screen sizes.

So to apply that to this instance, I think something like this should probably work
```html
<img
  src="/assets/images/ri-map-mobile.webp"
  srcset="/assets/images/ri-map-mobile.webp 350w,
          /assets/images/ri-map.webp
/>
```

2023-08-12 13:00 UTC, closed without merging